### ISSUE TITLE
litle bug in config editor

### ISSUE THREAD

**Issue by benoitLecuppe** [AndreasArvidsson/WinDSP#11]
Bonjour de France :-),
I use your product for active filtering beetwen Virtual DJ and a 5.1 hercule Muse pocket.
And it's work.
But, the config editor write the butterwoth order filter as string in json file and WinDSP want an integer.
So i must edit the json file after each modifcation in web interface

Thank for your  very very nice job

**Comment by AndreasArvidsson** [comment]
Hej ifrån Sverige :)
Glad to hear that you have use of the software. 

Oh I will have a look at that as soon as I have some spare time :)

**Comment by AndreasArvidsson** [comment]
This should be fixed in the latest release. Please try it out and thanks for finding this bug :)

https://github.com/AndreasArvidsson/WinDSP/releases/tag/1.0.0
